
version: "3.8"
services:
  gpu-exporter:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # For Docker Compose with NVIDIA toolkit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # If not using Swarm, you may need to uncomment the following line instead:
    # runtime: nvidia
