
version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
