version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - VITE_PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: bridge

  gpu-exporter:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # Ensure GPUs are accessible in non-Swarm Docker Compose
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Share host PID namespace so nvidia-smi/NVML can see host processes
    pid: "host"
    # Additional privileges for process detection
    privileged: true
    volumes:
      - /proc:/host/proc:ro
